server:
  port: 8101

spring:
  application:
    name: my-ribbon-loadbalance

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
