server:
  port: 8082

spring:
  application:
    name: my-feign-provider
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
